name: fluchat
description: Chat App implemented using Clean Architecture to PGCEEL.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.5
  #stream_chat_flutter: ^7.2.0
  connectivity_plus: 5.0.2
  stream_chat_flutter: 7.2.0-hotfix.1
  uuid: ^4.4.0

  firebase_core: ^2.29.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.19.1
  firebase_storage: ^11.7.1
  shared_preferences: ^2.2.3
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/